---
name: "terraform-docs"

on:
  pull_request:

jobs:
  terraform-docs:
    uses: GersonRS/modern-gitops-stack/.github/workflows/modules-terraform-docs.yaml@main
    with:
      variants: "aks,eks,kind,nodeport,scaleway,sks"
